version: '3.8'

services:
  golang-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/projects
    ports:
      - "3000-4000:3000-4000"
    container_name: go-lab
    tty: true 