---
- name: Setup Kubernetes
  become: true
  block:

    - name: Ensure /etc/apt/keyrings directory exists (for older Ubuntu/Debian versions)
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download and store Kubernetes signing key
      become: true
      ansible.builtin.shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Set correct permissions for the signing key
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        mode: "0644"

    - name: Add Kubernetes APT repository
      become: true
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /\n"
        mode: "0644"

    - name: Update APT cache
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Install kubectl, kubelet, kubeadm
      become: true
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
        state: present
