# Default target
all:

# Install
apply:
	ansible-playbook apply.yaml # --ask-become-pass --ask-pass
# Help message
help:
	@echo "Usage:"
	@echo "  make apply				# Configure control and nodes for Kubernets cluster"
