---
- name: Configure server for Kubernetes
  hosts: k8s_cluster
  become: yes

  roles:
    - role: hostname
    - role: ssh
    - role: network
    - role: cloudinit
    - role: packages
    - role: multipathd
    - role: containerd
    - role: swap
    - role: reboot
