- name: Install K3s server with SQLite
  hosts: control
  become: true
  tasks:
    - name: Install K3s server (default with SQLite)
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable servicelb" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Copy K3s token to local machine
      fetch:
        src: /var/lib/rancher/k3s/server/node-token
        dest: ./k3s_token
        flat: true

    - name: Get server IP
      set_fact:
        k3s_server_ip: "{{ ansible_host }}"

    - name: Copy kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig.yaml
        flat: true

- name: Install K3s agents
  hosts: nodes
  become: true
  vars:
    k3s_server_ip: "{{ groups['control1'][0] }}"
  tasks:
    - name: Read token from local file
      slurp:
        src: ./k3s_token
      register: k3s_token_raw
      delegate_to: localhost
      become: false

    - name: Debug K3s token
      debug:
        msg: "K3s server IP is {{ k3s_token_raw }}"

    - name: Decode token
      set_fact:
        k3s_token: "{{ k3s_token_raw.content | b64decode }}"

    - name: Install K3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ k3s_server_ip }}:6443 K3S_TOKEN={{ k3s_token }} INSTALL_K3S_EXEC="agent" sh -
      args:
        creates: /usr/local/bin/k3s-agent
