---
- name: Clean virtual machine before converting it into template
  hosts: virtual_machine
  become: yes

  roles:
    - role: packages
    - role: cloudinit
    - role: ssh
    - role: machine_id
