# Default target
all:

cleanup:
	ansible-playbook cleanup.yaml --ask-pass --ask-become-pass

# Help message
help:
	@echo "Usage:"
	@echo "  make cleanup							# Cleanup machine before converting into template"
