---
- name: Check if machine is proxmox VM
  ansible.builtin.debug:
    msg: "This is not a Proxmox system!"
  when: not proxmox_vm | default(false) | bool

- name: Cleanup cloud-init
  become: true
  become_user: root
  when: proxmox_vm | default (false)
  block:

    - name: Run cloud-init clean
      ansible.builtin.command:
        cmd: cloud-init clean
      changed_when: false  # Avoids marking the task as changed unnecessarily

    - name: Remove cloud-init instances directory
      ansible.builtin.file:
        path: /var/lib/cloud/instances
        state: absent
