---
- name: Install packages for "Archlinux"
  become: true
  become_user: root
  when: ansible_os_family == "Archlinux"
  block:
    - name: Execute Archlinux tasks
      ansible.builtin.include_tasks: archlinux/main.yaml

- name: Install packages for "Debian/Ubuntu"
  become: true
  become_user: root
  when: ansible_os_family == "Debian"
  block:
    - name: Execute Debian tasks
      ansible.builtin.include_tasks: debian/main.yaml

- name: Install packages for "Windows"
  when: ansible_os_family == "Windows"
  block:
    - name: Execute Windows tasks
      ansible.builtin.include_tasks: windows/main.yaml
