---
- name: Proxmox package installation
  become: true
  block:
    - name: Load variable file
      ansible.builtin.include_vars: proxmox.yaml

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Clean APT cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: true
