---
- name: Make sure required packages are present
  become: true
  block:
    - name: Load variable file
      ansible.builtin.include_vars: ubuntu.yaml

    - name: Add Helm GPG key
      ansible.builtin.shell:
        cmd: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        creates: /usr/share/keyrings/helm.gpg

    - name: Add Helm APT repository
      ansible.builtin.shell:
        cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        creates: /etc/apt/sources.list.d/helm-stable-debian.list

    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"

    - name: Clean APT cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: true
