version: '3.6'
services:
  gitlab:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - '/srv/portainer/data:/data'
      - /var/run/docker.sock:/var/run/docker.sock
