---
- name: Configure server for Kubernetes
  hosts: k8s_cluster
  become: yes

  roles:
    - role: hostname
    - role: packages
    - role: containerd
    - role: swap
    - role: network
    - role: reboot
    - role: kubernetes
