---
- name: Setup network
  become: true
  block:

    - name: Uncomment net.ipv4.ip_forward=1 in /etc/sysctl.conf
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        regexp: '^#\s*(net\.ipv4\.ip_forward\s*=\s*1)'
        line: 'net.ipv4.ip_forward=1'
        backrefs: true

    - name: Copy k8s.conf file
      ansible.builtin.copy:
        src: k8s.conf
        dest: /etc/modules-load.d/k8s.conf
        owner: root
        group: root
        mode: '0666'
