---
- name: Setup network
  become: true
  block:
    - name: Disable IPv6 system-wide
      ansible.builtin.sysctl:
        name: "{{ item }}"
        value: "1"
        state: present
        reload: true
        sysctl_set: true
        sysctl_file: /etc/sysctl.d/99-disable-ipv6.conf
      loop:
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.lo.disable_ipv6

    - name: Disable Ethernet Flow Control (RX & TX)
      ansible.builtin.command: ethtool -A eth0 rx off tx off

    - name: Force Full-Duplex Mode (100 Mbps, Full)
      ansible.builtin.command: ethtool -s eth0 speed 100 duplex full autoneg off

    - name: Create systemd service to persist settings
      ansible.builtin.copy:
        src: disable-flow-control.service
        dest: /etc/systemd/system/disable-flow-control.service
        mode: '0644'
      notify:
        - Reload systemd
        - Enable and start service
