---
- name: Setup network for "Ubuntu"
  become: true
  become_user: root
  when: ansible_distribution == "Ubuntu"
  block:

    - name: Setup network
      ansible.builtin.include_tasks: ubuntu.yaml
