- name: Get variable files
  ansible.builtin.include_vars:
    file: ubuntu.yaml

- name: Update and upgrade apt
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist

- name: Determine profiles to install
  ansible.builtin.set_fact:
    selected_profiles: "{{ [profile] if profile is defined else vars.keys() | list }}"

- name: Install APT packages
  ansible.builtin.apt:
    name: "{{ item.1.name }}"
    state: "{{ item.1.state | default('latest') }}"
  with_subelements:
    - "{{ selected_profiles | map('extract', vars) | selectattr('apt', 'defined') | list }}"
    - apt
  when: item.1 is defined
  loop_control:
    label: "{{ item.1.description }}"

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item.1.name }}"
    state: "{{ item.1.state | default('latest') }}"
  with_subelements:
    - "{{ selected_profiles | map('extract', vars) | selectattr('pip', 'defined') | list }}"
    - pip
  when: item.1 is defined
  loop_control:
    label: "{{ item.1.description }}"

- name: Install snap packages
  community.general.snap:
    name: "{{ item.1.name }}"
    classic: "{{ item.1.classic | default(false) }}"
    state: "{{ item.1.state | default('latest') }}"
  with_subelements:
    - "{{ selected_profiles | map('extract', vars) | selectattr('snap', 'defined') | list }}"
    - snap
  when: item.1 is defined
  loop_control:
    label: "{{ item.1.description }}"