---
- name: Update and Upgrade System
  become: true
  block:
    - name: Update apt package list
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
    - name: Install packages
      ansible.builtin.apt:
        name:
          - containerd
          - qemu-guest-agent
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present
    - name: Clean APT cache
      ansible.builtin.apt:
        autoclean: true
    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: true
