---
all:
  children:
    localhost:
      ansible_connection: local

    k3s_cluster:
      children:
        server1:
          hosts:
            192.168.10.11:
              desired_hostname: control1
        agent:
          children:
            agent1:
              hosts:
                192.168.10.21:
                  desired_hostname: server1
            agent2:
              hosts:
                192.168.10.22:
                  desired_hostname: server2

      vars:
        ansible_port: 22
        ansible_user: ansible
        # ansible_password: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        desired_password: ansible
        ansible_ssh_private_key_file: ~/.ssh/k3s_homelab_ed25519
