---
all:
  children:
    localhost:
      ansible_connection: local
    remote_windows:
      hosts:
        192.168.10.11:
  vars:
    ansible_port: 22
    ansible_user: ansible
    # ansible_password: root
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    desired_password: ansible
    ansible_ssh_private_key_file: ~/.ssh/private_key_ed25519
