---
all:
  children:
    # localhost:
    #   ansible_connection: local
    #   ansible_user: user
    remote_windows:
      hosts:
        192.168.1.100:
      vars:
        ansible_port: 5985
        ansible_user: user
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
  vars:
    ansible_port: 22
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    desired_password: ansible
    ansible_ssh_private_key_file: ~/.ssh/private_key_ed25519
