archlinux:
  groups:
    - name: g_gitlab
    - name: g_docker_services
    - name: g_projects
    - name: g_shared_directory
  users:
    - name: u_remote_directories
      comment: System user to own and sync directories
      group: g_shared_directory
      groups:
    - name: u_docker_services
      comment: System user to docker services
      group: g_docker_services
      groups: g_gitlab,docker
  directories:
    - path: /shared
      description: Shared Directory
      group: g_shared_directory
      mode: '0774'
    - path: /shared/src
      description: Projects Directory
      group: g_projects
      mode: '0770'
    - path: /shared/cloud
      description: Cloud directories
      owner: u_remote_directories
      group: g_shared_directory
      mode: '0774'
    - path: /srv/golang-lab
      description: Docker files for golang environment applications
      owner: u_docker_services
      group: g_docker_services
    - path: /srv/gitlab
      description: GitLab Home Directory
      group: g_gitlab
    - path: /srv/gitlab/data
      description: Stores GitLab application data
      group: root # gitlab changes automatically
      mode: '0755' # gitlab changes automatically
    - path: /srv/gitlab/logs
      description: Stores GitLab logs
      group: root # gitlab changes automatically
      mode: '0755' # gitlab changes automatically
    - path: /srv/gitlab/config
      description: Stores GitLab configuration files
      group: root # gitlab changes automatically
      mode: '0775' # gitlab changes automatically
  files:
    - src: files/golang/Dockerfile
      dest: /srv/golang-lab/Dockerfile
      owner: u_docker_services
      group: g_docker_services
    - src: files/golang/docker-compose.yml
      dest: /srv/golang-lab/docker-compose.yml
      owner: u_docker_services
      group: g_docker_services
    - src: files/gitlab/docker-compose.yml
      dest: /srv/gitlab/docker-compose.yml
      owner: u_docker_services
      group: g_docker_services
  services:
    execute:
#    - name: gdm.service
#      description: Enable gnome desktop manager
    - name: docker.service
      description: Enable Docker service
    - name: gitlab.service
      description: Enable Gitlab service
    template:
    - name: golang-lab
      template_path: templates/docker-compose-service.j2
      description: "Docker Compose Service for Golang Tools"
      user: u_docker_services
      working_directory: /srv/golang-lab
    - name: gitlab
      template_path: templates/docker-compose-service.j2
      description: "Docker Compose Service for Gitlab local instance"
      user: u_docker_services
      working_directory: /srv/gitlab
