---
all:
  children:
    localhost:
      ansible_connection: local
      ansible_user: user
    remote_windows:
      hosts:
        192.168.1.10:
      vars:
        ansible_port: 5985
        ansible_user: user
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
  vars:
    ansible_port: 22
    desired_password: ansible
