version: '3.6'
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    environment:
     - GF_SERVER_ROOT_URL=http://my.grafana.server/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
      - '/srv/grafana/data:/var/lib/grafana'