- name: Get variable files
  ansible.builtin.include_vars:
    file: windows/packages.yaml

- name: Install Chocolatey (if needed)
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present

- name: Install Chocolatey packages for selected or all profiles
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
  loop: >-
    {{
      (choco_packages[(selected_profile | default(''))] 
        if (selected_profile | default('') in choco_packages) 
        else choco_packages.values() | flatten)
    }}
  loop_control:
    label: "{{ item.name }}"

- name: Upgrade installed packages
  chocolatey.chocolatey.win_chocolatey:
    name: all
    state: latest

- name: Expand system_path_entries with ansible_user
  set_fact:
    resolved_path_entries: >-
      {{ system_path_entries | map('regex_replace', '\{\{\s*ansible_user\s*\}\}', ansible_user) | list }}

- name: Ensure key application paths are in system PATH
  win_environment:
    state: present
    name: PATH
    level: machine
    value: "{{ item }}"
    separator: ';'
  loop: "{{ system_path_entries }}"
  notify: Reboot Windows system

- name: Install pip packages
  ansible.windows.win_shell: pip install {{ item }}
  loop:
    - passlib