- name: Get variable files
  ansible.builtin.include_vars:
    file: windows/packages.yaml

- name: Install Chocolatey (if needed)
  chocolatey.chocolatey.win_chocolatey:
    name: chocolatey
    state: present

- name: Install Chocolatey packages
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name }}"
    state: present
  loop: "{{ choco_packages[selected_profile] }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure pip is installed (comes with python3)
  chocolatey.chocolatey.win_chocolatey:
    name: python3
    state: present

- name: Install pip packages
  ansible.windows.win_shell: pip install {{ item }}
  loop:
    - passlib