---
- name: Install packages
  hosts: local
  tags: prereqs
  vars_files:
  - properties.yaml
  
  tasks:
  - name: Install packages for "Archlinux"
    block:

    - name: Enable multilib repository in pacman.conf
      lineinfile:
        path: /etc/pacman.conf
        state: present
        regexp: '^#\[multilib\]'
        line: '[multilib]'

    - name: Enable multilib include line in pacman.conf
      lineinfile:
        path: /etc/pacman.conf
        state: present
        regexp: '^#Include = /etc/pacman.d/mirrorlist'
        line: 'Include = /etc/pacman.d/mirrorlist'

    - name: Update and upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: "Pacman: Install packages"
      community.general.pacman:
        name: "{{ item.name }}"
        state: "{{ item.state | default('latest') }}"
      loop: "{{ archlinux.packages.pacman }}"
      loop_control:
        label: "{{ item.description }}"

    - name: Install yay
      ansible.builtin.include_tasks: subtasks/yay_install.yaml

    - name: Update and upgrade yay
      community.general.pacman:
        update_cache: true
        upgrade: true
        executable: yay
        # extra_args: --builddir /var/cache/yay

    - name: "Yay: Install packages"
      community.general.pacman:
        name: "{{ item.name }}"
        state: "{{ item.state | default('latest') }}"
        executable: yay
        # extra_args: --builddir /var/cache/yay
      loop: "{{ archlinux.packages.yay }}"

    become: yes
    become_user: root
    when: ansible_os_family == "Archlinux"

  - name: Configure groups, users, access
    block:
    - name: Create groups
      ansible.builtin.group:
        name: "{{ item.name }}"
        system: "{{ item.system | default('false') | bool }}"
      loop: "{{ archlinux.groups }}"

    - name: Create users
      ansible.builtin.user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        append: "{{ item.append | default('false') | bool }}"
        group: "{{ item.group }}"
        groups: "{{ item.groups }}"
        create_home: "{{ item.create_home | default('false') | bool }}"
        system: "{{ item.system | default('true') | bool }}"  
      loop: "{{ archlinux.users }}"

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state | default('directory') }}"
        mode: "{{ item.mode | default('0660') }}"
        owner: "{{ item.owner | default('root') }}"
        group: "{{ item.group }}"
      loop: "{{ archlinux.directories }}"
    become: yes
    become_user: root

  - name: Copy files
    block:
      - name: Copy docker files
        ansible.builtin.copy:
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: "{{ item.owner }}"
          group: "{{ item.group }}"
          mode: "{{ item.mode | default('0640') }}"
        loop: "{{ archlinux.files }}"
    become: yes
    become_user: root

  - name: Configure services
    block:

    - name: Generate systemd services from templates
      ansible.builtin.template:
        src: "{{ item.template_path }}"
        dest: /etc/systemd/system/{{ item.name }}.service
        mode: '0644'
      loop: "{{ archlinux.services.template }}"
      loop_control:
        label: "{{ item.description }}"

    - name: Issue systemd daemon-reload to pick up config changes
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable services
      ansible.builtin.systemd_service:
        name: "{{ item.name }}"
        state: "{{ item.state | default('started') }}"
        enabled: "{{ item.state | default('true') | bool}}"
      loop: "{{ archlinux.services.execute }}"

    - name: Init starship
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^eval "\$\(starship init bash\)"'
        line: eval "$(starship init bash)"
      become: false

    become: yes
    become_user: root
