---
- name: Install packages
  hosts: local
  tags: prereqs
  vars_files:
  - packages.yaml
  
  tasks:
  - name: Install packages for "Archlinux"
    block:

    - name: Update and upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: "Pacman: Install packages"
      community.general.pacman:
        name: "{{ item.name }}"
        state: "{{ item.state | default('latest') }}"
      loop: "{{ archlinux.packages.pacman }}"

    - name: Enable gnome desktop manager
      ansible.builtin.systemd_service:
        name: gdm.service
        state: started
        enabled: true

    - name: Install yay
      ansible.builtin.include_tasks: subtasks/yay_install.yaml

    - name: Update and upgrade yay
      community.general.pacman:
        update_cache: true
        upgrade: true
        executable: yay
        extra_args: --builddir /var/cache/yay

    - name: "Yay: Install packages"
      community.general.pacman:
        name: "{{ item.name }}"
        state: "{{ item.state | default('latest') }}"
        executable: yay
        extra_args: --builddir /var/cache/yay
      loop: "{{ archlinux.packages.yay }}"

    - name: Init starship
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: '^eval "\$\(starship init bash\)"'
        line: eval "$(starship init bash)"
      become: false

    become: yes
    become_user: root
    when: ansible_os_family == "Archlinux"