---
- name: Install packages
  hosts: local
  tags: prereqs
  vars_files:
  - packages.yaml
  
  tasks:
  - name: Install packages for "Archlinux"
    block:

    - name: Update and upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: "Pacman: Install packages"
      community.general.pacman:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ archlinux.packages.pacman }}"

    - name: Enable gnome desktop manager
      ansible.builtin.systemd_service:
        name: gdm.service
        state: started
        enabled: true

    - name: Check if yay is present
      ansible.builtin.command: yay --version
      register: yay_version
      become: false

    - name: Clone "yay" repository
      ansible.builtin.git: 
        dest: ~/Projects/yay
        repo: https://aur.archlinux.org/yay.git
      become: false
      when: not yay_version.stdout is regex('^yay\s\w\d+\.\d+\.\d+\s-\s\w+\s\w\d+\.\d+\.\d+$')

    - name: Install "yay"
      ansible.builtin.command: chdir=~/Projects/yay makepkg --noconfirm -si        
      become: false
      when: not yay_version.stdout is regex('^yay\s\w\d+\.\d+\.\d+\s-\s\w+\s\w\d+\.\d+\.\d+$')

    - name: "Yay: Install packages"
      community.general.pacman:
        name: hyprland
        state: latest
        executable: yay
        extra_args: --builddir /var/cache/yay
      loop: "{{ archlinux.packages.yay }}"

    become: yes
    become_user: root
    when: ansible_os_family == "Archlinux"