---
- name: Install packages
  hosts: local
  tags: prereqs
  
  tasks:
  - name: Install packages for "Archlinux"
    block:

    - name: Update and upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install "gnome" desktop environment
      community.general.pacman:
        name: gnome
        state: latest

    - name: Enable gnome desktop manager
      ansible.builtin.systemd_service:
        name: gdm.service
        state: started
        enabled: true

    - name: Install "base-devel" package
      community.general.pacman:
        name: base-devel
        state: latest

    - name: Clone "yay" repository
      ansible.builtin.git: 
        dest: /usr/share/yay_repo
        repo: https://aur.archlinux.org/yay.git

    - name: Install "yay"
      ansible.builtin.command: chdir=/usr/share/yay_repo makepkg --noconfirm -si        

    - name: Install "alacritty" terminal emulator
      community.general.pacman:
        name: alacritty
        state: latest

    become: yes
    become_user: root
    when: ansible_os_family == "Archlinux"