archlinux:
  packages:
    pacman:
    - name: gnome
      description: Install "gnome" desktop environment
    - name: polkit-gnome
      description: Install "polkit-gnome" authentication framework
    - name: base-devel
      description: Install "base-devel" package
    - name: alacritty
      description: Install "alacritty" terminal emulator
    - name: starship
      description: Install "starship" customizable command prompt
    - name: tmux
      description: Install "tmux" terminal multiplexer
    - name: stow
      description: Install GNU "stow" symlink farm manager
    - name: neovim
      description: Install "neovim" text editor
    - name: lsd
      description: Install "lsd" replacement for ls
    - name: lazygit
      description: Install "lazygit" for graphical interaction in terminal
    - name: fzf
      description: Install "fzf" for fuzzy finding 
    - name: thunderbird
      description: Install "thunderbird" mail, news and chat client from Mozilla
    yay:
    - name: yazi
      description: Install "yazi" file manager
    - name: ttf-meslo-nerd
      description: Install "ttf-meslo-nerd" fonts
    - name: picom
      description: Install "picom" a lightweight compositor for X11
    - name: polybar
      description: Install "polybar" status bar for i3
    - name: feh
      description: Install "feh" a lightweight image viewer
    - name: rofi
      description: Install "rofi" a window switcher, application launcher
    - name: google-chrome
      description: Install "google-chrome" browser