---
- name: Configure and Install Cluster
  hosts: k3s_cluster
  become: yes

  roles:
    - role: hostnames
      tags: [hostname]

    - role: configure_ssh
      tags: [ssh]

    - role: change_password
      tags: [password]
