archlinux:
  groups:
    - name: g_gitlab
    - name: g_portainer
    - name: g_grafana
    - name: g_docker_services
    - name: g_projects
    - name: g_shared_directory
  users:
    - name: u_remote_directories
      comment: System user to own and sync directories
      group: g_shared_directory
      groups:
    - name: u_docker_services
      comment: System user to docker services
      group: g_docker_services
      groups: g_gitlab,g_portainer,g_grafana,docker
  directories:
    - path: /shared
      description: Shared Directory
      group: g_shared_directory
      mode: '0774'
    - path: /shared/src
      description: Projects Directory
      group: g_projects
      mode: '0770'
    - path: /shared/cloud
      description: Cloud directories
      owner: u_remote_directories
      group: g_shared_directory
      mode: '0774'
    - path: /srv/grafana
      description: Docker files for Grafana application
      owner: u_docker_services
      group: g_grafana
      mode: '0777'
    - path: /srv/grafana/data
      description: Stores Grafana application data
      owner: u_docker_services
      group: g_grafana
      mode: '0777'
    - path: /srv/portainer
      description: Docker files for Portainer application
      owner: u_docker_services
      group: g_portainer
    - path: /srv/portainer/data
      description: Stores Portainer application data
      owner: u_docker_services
      group: g_portainer
    - path: /srv/golang-lab
      description: Docker files for golang environment applications
      owner: u_docker_services
      group: g_docker_services
    - path: /srv/gitlab
      description: GitLab Home Directory
      group: g_gitlab
    - path: /srv/gitlab/data
      description: Stores GitLab application data
      group: root # gitlab changes automatically
      mode: '0755' # gitlab changes automatically
    - path: /srv/gitlab/logs
      description: Stores GitLab logs
      group: root # gitlab changes automatically
      mode: '0755' # gitlab changes automatically
    - path: /srv/gitlab/config
      description: Stores GitLab configuration files
      group: root # gitlab changes automatically
      mode: '0775' # gitlab changes automatically
  files:
    - src: files/grafana/docker-compose.yml
      dest: /srv/grafana/docker-compose.yml
      owner: u_docker_services
      group: g_docker_services
    - src: files/portainer/docker-compose.yml
      dest: /srv/portainer/docker-compose.yml
      owner: u_docker_services
      group: g_docker_services
    - src: files/golang/Dockerfile
      dest: /srv/golang-lab/Dockerfile
      owner: u_docker_services
      group: g_docker_services
    - src: files/golang/docker-compose.yml
      dest: /srv/golang-lab/docker-compose.yml
      owner: u_docker_services
      group: g_docker_services
    - src: files/gitlab/docker-compose.yml
      dest: /srv/gitlab/docker-compose.yml
      owner: u_docker_services
      group: g_docker_services
  packages:
    pacman:
#    - name: gnome
#      description: Install "gnome" desktop environment
#    - name: gnome-tweaks
#      description: Install "gnome-tweaks"
#    - name: gdm
#      description: Install "gdm" greeter
    - name: dolphin
      description: Install "dolphin" KDE's file manager
    - name: dunst
      description: Install "dunst" notification system
    - name: grim
      description: Install "grim" console utility to make Wayland screenshots
    - name: hyprland
      description: Install "hyprland" window manager
    - name: polkit-kde-agent
      description: Install "polkit-kde-agent" daemon providing a polkit authentication UI for KDE
    - name: qt5-wayland
      description: Install "qt5-wayland" QtWayland platform plugin for Qt5 applications
    - name: qt6-wayland
      description: Install "qt6-wayland" QtWayland platform plugin for Qt6 applications
    - name: slurp
      description: Install "slurp" cli utility to select a region in a Wayland compositor
    - name: brightnessctl
      description: Install "brightnessctl" to change screen brightness
    - name: wofi
      description: Install "wofi" application launcher
    - name: xdg-desktop-portal-gtk
      description: Install "xdg-desktop-portal-gtk" backend implementation using GTK
    - name: xdg-desktop-portal-hyprland
      description: Install "xdg-desktop-portal-hyprland" an XDG Desktop Portal backend for Hyprland
    - name: polkit-gnome
      description: Install "polkit-gnome" authentication framework
    - name: xorg-xhost
      description: Install "xorg-xhost" server access control program for X
    - name: waybar
      description: Instlall "waybar" wayland bar for sway
    - name: swaync
      description: Install "swaync" notification window
    - name: hyprpaper
      description: Install "hyprpaper" wallpaper for hyprland
    - name: base-devel
      description: Install "base-devel" package
    - name: less
      description: Install "less" pager
    - name: gparted
      description: Install "gparted" partition tools software
    - name: gpart
      description: Install "gpart" storage scanner
    - name: nilfs-utils
      description: Install "nilfs-utils" log structured file system
    - name: jfsutils
      description: Install "jfsutils" jfs file system utilities
    - name: ntfsprogs
      description: Install "ntfsprogs" utilities for managing ntfs
    - name: reiserfsprogs
      description: Install "reiserfsprogs" reiserfs utilities
    - name: xfsprogs
      description: Install "xfsprogs" xfs filesystem utilities
    - name: alacritty
      description: Install "alacritty" terminal emulator
    - name: kitty
      description: Install "kitty" terminal emulator
    - name: pipewire
      description: Install "pipewire" audio and video stream handler
    - name: starship
      description: Install "starship" customizable command prompt
    - name: tmux
      description: Install "tmux" terminal multiplexer
    - name: stow
      description: Install GNU "stow" symlink farm manager
    - name: neovim
      description: Install "neovim" text editor
    - name: lsd
      description: Install "lsd" replacement for ls
    - name: lazygit
      description: Install "lazygit" for graphical interaction in terminal
    - name: fzf
      description: Install "fzf" for fuzzy finding 
    - name: thunderbird
      description: Install "thunderbird" mail, news and chat client from Mozilla
    - name: keepass
      description: Install "keepass" pasword manager
    - name: calibre
      description: Install "calibre" e-book management system
    - name: firefox
      description: Install "firefox" web browser
    - name: rclone
      description: Install "rclone" sinchronization utility
    - name: qbittorrent
      description: Install "qbittorrent" torrent transfer application
    - name: docker
      description: Install "docker" container service
    - name: docker-compose
      description: Install "docker-compose" container manager
    - name: telegram-desktop
      description: Install "telegram-desktop" messenger service
    - name: discord
      description: Install "discord" messenger service
    - name: virtualbox-host-modules-arch
      description: Install "virtualbox-host-modules-arch" kernel interaction modules
    - name: virtualbox
      description: Install "virtualbox" hypervisor
    - name: vagrant
      description: Install "vagrant" virtual environment manager
    - name: libreoffice-fresh
      description: Install "libreoffice-fresh" office suite applications
    - name: vlc 
      description: Install "vlc" media player
    - name: gimp
      description: Install "gimp" image editor
    - name: code
      description: Install Visual "code" text editor
    - name: krita
      description: Install "krita" image editor
    - name: cmus
      description: Install "cmus" console audio player
    - name: steam
      description: Install "steam" game distribution service
    - name: npm
      description: Install "npm" node packet manager
    - name: nodejs 
      description: Install "nodejs" js runtime
    - name: go
      description: Install "go" compiler and development tools
    - name: sqlitebrowser 
      description: Install "sqlitebrowser" sqlite db browser
    - name: p7zip
      description: Install "p7zip" compression utility
    yay:
    - name: yazi
      description: Install "yazi" file manager
    - name: ttf-meslo-nerd
      description: Install "ttf-meslo-nerd" fonts
    - name: picom
      description: Install "picom" a lightweight compositor for X11
    - name: polybar
      description: Install "polybar" status bar for i3
    - name: feh
      description: Install "feh" a lightweight image viewer
    - name: rofi
      description: Install "rofi" a window switcher, application launcher
  services:
    execute:
#    - name: gdm.service
#      description: Enable gnome desktop manager
    - name: docker.service
      description: Enable Docker service
    - name: gitlab.service
      description: Enable Gitlab service
    - name: portainer.service
      description: Enable Portainer service
    - name: grafana.service
      description: Enable Grafane service
    template:
    - name: golang-lab
      template_path: templates/docker-compose-service.j2
      description: "Docker Compose Service for Golang Tools"
      user: u_docker_services
      working_directory: /srv/golang-lab
    - name: gitlab
      template_path: templates/docker-compose-service.j2
      description: "Docker Compose Service for Gitlab local instance"
      user: u_docker_services
      working_directory: /srv/gitlab
    - name: portainer
      template_path: templates/docker-compose-service.j2
      description: "Docker Compose Service for Portainer application"
      user: u_docker_services
      working_directory: /srv/portainer
    - name: grafana
      template_path: templates/docker-compose-service.j2
      description: "Docker Compose Service for Grafana application"
      user: u_docker_services
      working_directory: /srv/grafana
