---
- name: Remove SSH host keys
  become: true
  become_user: root
  block:

    - name: Delete all SSH host key files
      ansible.builtin.file:
        path: "/etc/ssh/{{ item }}"
        state: absent
      with_fileglob:
        - "/etc/ssh/ssh_host_*"

    - name: Ensure PubkeyAuthentication is enabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present
      notify: Restart SSH

    - name: Ensure .ssh directory exists
      become: false
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: '0700'

    - name: Add SSH Public Key to authorized_keys
      ansible.builtin.authorized_key:
        user: "{{ ansible_user | default('root') }}"  # Ensure it’s the correct user
        key: "{{ ssh_public_key }}"
        state: present
