repositories:
  - name: nfs-provisioner
    url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    description: NFS storage class
  - name: metallb
    url: https://metallb.github.io/metallb
    description: Metallb load balancer
  - name: traefik
    url: https://traefik.github.io/charts
    description: Traefik ingress provider
  - name: cert-manager
    url: https://charts.jetstack.io
    description: Kubernetes addon for managing certificates
  - name: pihole
    url: https://mojo2600.github.io/pihole-kubernetes
    description: DNS sinkhole
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard
    description: Kubernetes dashboard
  - name: plex
    url: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    description: Plex media server
ingress:
  - name: pihole
    namespace: dns-pihole
    hostname: pihole.cloud.lan
    service: pihole-web
    port: 80
  # - name: traefik
  #   namespace: dns-pihole
  #   hostname: pihole.cloud.lan
  #   service: pihole-web
  #   port: 80
  - name: plex
    namespace: media-services
    hostname: plex.cloud.lan
    service: plex-plex-media-server
    port: 32400
  - name: k8s-dashboard
    namespace: kube-utility
    hostname: k8s-dashboard.cloud.lan
    service: k8s-dashboard-kong-proxy
    port: 443
  - name: argocd
    namespace: argocd
    hostname: argocd.cloud.lan
    service: argocd-server
    port: 443
