helm:
  # - name: plex
  #   chart: plex/plex-media-server
  #   version: 0.9.1
  #   namespace: media-services
  # - name: kavita
  #   chart: truecharts/kavita
  #   version: 1.0.7
  #   namespace: media-services
manifest:
  # - gitlab-token.yaml.j2
  # - k8s-dashboard-account.yaml.j2
  # - k8s-dashboard-rolebinding.yaml.j2
  # - k8s-dashboard-secret.yaml.j2
